name: interview_coach_app
description: Automated Interview Prep Coach - Duolingo-style (Purple-Pink Gradient)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  file_picker: 8.0.0   # FIXED for Windows
  path_provider: ^2.1.3
  permission_handler: ^12.0.1

  # Audio & camera
  record: 6.1.2       # Windows safe fallback (no audio)
  camera: ^0.10.5+9

  # UI
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11

  uuid: ^4.4.0

  pdf: ^3.10.1
  printing: ^5.10.0
  share_plus: 12.0.1
  intl: ^0.20.2
  open_filex: ^4.7.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
